name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Release Name
        id: set_release_name
        run: echo "::set-output name=release_name::Release ${{ github.sha }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/*.exe
          tag_name: ${{ github.sha }}
          token: ${{ secrets.REPO_TOKEN }}
