name: Create Release

on:
  push:
    branches:
      - main  # Adjust the branch name to your specific branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

  create_release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Upload Executables
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: build/*.exe

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}  # Use a unique identifier, e.g., commit SHA, as the tag name
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
